name: file_storage
description: "Cross-platform file storage."
version: 1.0.0
homepage: https://github.com/darkstarx/file_storage

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  idb_shim: ^2.6.1+7
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: null
