name: file_storage
description: "Cross-platform file storage."
version: 0.0.1
homepage: https://github.com/darkstarx/file_storage

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  idb_shim: ^2.4.1+1
  path: ^1.9.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: null
